--- CLEANING AND ADD CONSTRAINTS ON JOB Table --- Chỉ cần thêm ràng buộc toàn vẹn bảng này, vì các bảng khác dữ liệu đa phần là độc lập

-- 1. SALARY: EDA xem lương có bị tính sai khoảng thời gian (theo năm/ tháng/tuần)
SELECT JOB.JOB_ID, JOB.SALARY_MAX 
FROM JOB
ORDER BY JOB.SALARY_MAX DESC

SELECT JOB_ID, SALARY_MAX 
FROM JOB
WHERE SALARY_MAX > 500000000

DELETE FROM JOB -- Cần đảm bảo đã cài đặt Trigger xóa liên đới từ JOB_DETAIL khi xóa JOB
WHERE SALARY_MAX > 500000000

-- 2. SALARY: ADD CONSTRAINTS SALARY_MIN <= SALARY_MAX
ALTER TABLE JOB ADD CONSTRAINT CK_SALARY_MIN_MAX 
CHECK (SALARY_MIN <= SALARY_MAX);

-- 3. SALARY: Tạo 1 cột SALARY là trung bình giữa SALARY_MIN và SALARY_MAX
ALTER TABLE JOB
ADD SALARY_COMPUTED AS (SALARY_MIN + (SALARY_MAX - SALARY_MIN) / 2.0);

SELECT COUNT(*) FROM JOB

-- 4. RECRUITMENT COUNT lớn hơn hoặc bằng 1
ALTER TABLE JOB ADD CONSTRAINT CK_RECRUITMENT_COUNT_MORETHAN_ONE
CHECK (RECRUITMENT_COUNT >= 1);

-- 5. WORK_ON_SATURDAY VÀ WORK_ON_SUNDAY chỉ nhận giá trị 0/1 - TRUE/FALSE
ALTER TABLE JOB ADD CONSTRAINT CK_WORK_ON_SATURDAY
CHECK (WORK_ON_SATURDAY IN (0, 1));

ALTER TABLE JOB ADD CONSTRAINT CK_WORK_ON_SUNDAY
CHECK (WORK_ON_SUNDAY IN (0, 1));

-- 6. TOTAL_WORK_HOURS phải lớn hơn 0
ALTER TABLE JOB ADD CONSTRAINT CK_TOTAL_WORK_HOURS
CHECK (TOTAL_WORK_HOURS > 0)

-- 7. FIRST_WORKING_DAY_OF_WEEK và LAST_WORKING_DAY_OF_WEEK phải thuộc từ 2 - 6. 
-- Lưu ý để xem job có làm thứ 7 hay không ta xem trường WORKING_ON_SATURDAY
-- SELECT DISTINCT FIRST_WORKING_DAY_OF_WEEK, LAST_WORKING_DAY_OF_WEEK FROM JOB

ALTER TABLE JOB ADD CONSTRAINT CK_FIRST_WORKING_DAY_OF_WEEK
CHECK (FIRST_WORKING_DAY_OF_WEEK >= 2 AND FIRST_WORKING_DAY_OF_WEEK <= 6)

ALTER TABLE JOB ADD CONSTRAINT CK_LAST_WORKING_DAY_OF_WEEK
CHECK (LAST_WORKING_DAY_OF_WEEK >= 2 AND LAST_WORKING_DAY_OF_WEEK <= 6)

-- 8. SALARY_MIN và SALARY_MAX phải lớn hơn 0. -1 cho trường hợp missing
--SELECT (SALARY_MIN)  FROM JOB
--ORDER BY SALARY_MIN 

ALTER TABLE JOB ADD CONSTRAINT CK_SALARY_MIN
CHECK (SALARY_MIN >= 0 OR SALARY_MIN = -1);

ALTER TABLE JOB ADD CONSTRAINT CK_SALARY_MAX
CHECK (SALARY_MAX >= 0 OR SALARY_MAX = -1);

